### ISSUE TITLE
Gradient norm

### ISSUE THREAD

**Issue by meobach** [mr-eggplant/SAR#11]
Hi author,
Thanks for your exciting paper!

I want to ask you how you have calculated the gradient norm in Figure 2.d. Did you run it on batch size 1 for estimating the gradient and its corresponding entropy?
Thank you!

**Comment by mr-eggplant** [comment]
Hi, thank you for your interest! Yes, Figure 2 d ran on batch size = 1.

**Comment by meobach** [comment]
Thank you for your quick response,
I am also curious about calculating the gradient norm for each sample, is it just a sum of gradients from all network parameters after each backward step?
Thank you!

**Comment by mr-eggplant** [comment]
Yes. 
total_grad_norm = 0
for name, param in model.named_parameters():
    if param.grad is not None:
        grad_norm_cur = torch.norm(param.grad.flatten())
        total_grad_norm += grad_norm_cur

**Comment by meobach** [comment]
Thank you so much!
