### ISSUE TITLE
TENT performance under imbalance shift with VIT-LN model

### ISSUE THREAD

**Issue by meobach** [mr-eggplant/SAR#12]
Dear authors,
Thank you for the interesting paper,

I have cloned your repo and ran it with the following command (I do not change anything in your code):
 python main.py --data_corruption ../imagenet --exp_type label_shifts --method tent --model vitbase_timm --output out.
The result of this command line should be similar to the result of the TENT model reported in Table.2 of your paper, under the VIT-base. However, I have found that the performance of TENT is not as bad as you have reported, the result when I run the first 5 corruption types is 47.8, 46.8, 48.4, 54.5, 52.3, which corresponds to gaussian_noise, shot noise, impulse noise, and defocus_blur. But the results in your paper for these corruption types are 32.7 1.4 34.6 54.4 and 52.3 ( its accuracy is similar to the two last corruption types).

**Comment by mr-eggplant** [comment]
Hi, you may reproduce the results using timm=0.6.11 and torch=1.8.0.     I also found this issue recently, using the latest timm and torch could get better results.

**Comment by meobach** [comment]
Thank you so much for your response!
